version: '3'
services:

  uos-publish-json:
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    image: abyss-publisher:lightweight
    container_name: uos-publish-json
    stdin_open: true  # equivalent to docker run -i
    tty: true         # equivalent to docker run -t
    volumes:
      # For persistent cache storage
      # - ./cache/transformers:/app/.cache/transformers
      # - ./cache/matplotlib:/app/.cache/matplotlib
      # If you need to mount configuration
      - uos-publish-json_config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: always
    networks:
      - mqtt-broker_toolbox-network

networks:
    mqtt-broker_toolbox-network:
      external: True

volumes:
  uos-publish-json_config:
    # driver: local