version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

volumes:
  mongodb_data:
    driver: local
  mongodb_logs:
    driver: local

