# CPU-only Docker Compose configuration
# Optimized for production deployment without CUDA dependencies

version: '3.8'

services:
  uos-depthest-listener-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        - PYTHON_VERSION=3.10.16
    image: uos-depthest-listener:cpu
    container_name: uos-depthest-listener-cpu
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - MPLCONFIGDIR=/app/.cache/matplotlib
      - HF_HOME=/app/.cache/transformers
      - TRANSFORMERS_CACHE=/app/.cache/transformers
    
    # Volume mounts for persistence and configuration
    volumes:
      # Configuration files
      - ./abyss/src/abyss/run/config:/app/config:ro
      # Persistent cache for models and libraries
      - uos_cpu_cache_transformers:/app/.cache/transformers
      - uos_cpu_cache_matplotlib:/app/.cache/matplotlib
      # Optional: Mount trained models if external
      # - ./abyss/src/abyss/trained_model:/app/trained_model:ro
    
    # Network configuration
    networks:
      - toolbox-network
    
    # Resource limits (CPU-only)
    deploy:
      resources:
        limits:
          cpus: '2.0'        # Limit to 2 CPU cores
          memory: 4G         # 4GB memory limit
        reservations:
          cpus: '0.5'        # Reserve at least 0.5 CPU
          memory: 1G         # Reserve 1GB memory
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import abyss; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # MQTT Broker (for testing - optional)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker-cpu-test
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt_config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_logs:/mosquitto/log
    networks:
      - toolbox-network

networks:
  toolbox-network:
    driver: bridge
    name: toolbox-network

volumes:
  uos_cpu_cache_transformers:
    driver: local
  uos_cpu_cache_matplotlib:
    driver: local
  mqtt_config:
    driver: local
  mqtt_data:
    driver: local
  mqtt_logs:
    driver: local